"""Initial schema

Revision ID: f868e8f93030
Revises: 
Create Date: 2026-07-11 11:43:09.017501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f868e8f93030'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_admins_email'), table_name='admins')
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.drop_index(op.f('idx_lead_followups_assigned_to'), table_name='lead_followups')
    op.drop_constraint(op.f('uq_lead_followups_lead_id'), 'lead_followups', type_='unique')
    op.create_index(op.f('ix_lead_followups_assigned_to'), 'lead_followups', ['assigned_to'], unique=False)
    op.drop_index(op.f('idx_leads_assigned_to'), table_name='leads')
    op.drop_index(op.f('idx_leads_created_at'), table_name='leads')
    op.drop_index(op.f('idx_leads_created_by'), table_name='leads')
    op.drop_index(op.f('idx_leads_current_owner'), table_name='leads')
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_created_by'), 'leads', ['created_by'], unique=False)
    op.create_index(op.f('ix_leads_current_owner'), 'leads', ['current_owner'], unique=False)
    op.drop_column('password_reset_otps', 'is_verified')
    op.drop_index(op.f('idx_payments_payment_date'), table_name='payments')
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.drop_index(op.f('idx_quotations_created_at'), table_name='quotations')
    op.drop_index(op.f('idx_quotations_customer_phone'), table_name='quotations')
    op.drop_constraint(op.f('uq_quotations_quote_number'), 'quotations', type_='unique')
    op.drop_index(op.f('ix_quotations_quote_number'), table_name='quotations')
    op.create_index(op.f('ix_quotations_quote_number'), 'quotations', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotations_created_at'), 'quotations', ['created_at'], unique=False)
    op.create_index(op.f('ix_quotations_customer_phone'), 'quotations', ['customer_phone'], unique=False)
    op.drop_index(op.f('uq_salesmen_email'), table_name='salesmen')
    op.create_index(op.f('ix_salesmen_email'), 'salesmen', ['email'], unique=True)
    op.drop_index(op.f('uq_telecallers_email'), table_name='telecallers')
    op.create_index(op.f('ix_telecallers_email'), 'telecallers', ['email'], unique=True)
    op.drop_index(op.f('idx_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('idx_user_sessions_is_revoked'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_revoked'), 'user_sessions', ['is_revoked'], unique=False)
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('uq_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('uq_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.drop_index(op.f('ix_user_sessions_is_revoked'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.create_index(op.f('idx_user_sessions_is_revoked'), 'user_sessions', ['is_revoked'], unique=False)
    op.create_index(op.f('idx_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_telecallers_email'), table_name='telecallers')
    op.create_index(op.f('uq_telecallers_email'), 'telecallers', ['email'], unique=True)
    op.drop_index(op.f('ix_salesmen_email'), table_name='salesmen')
    op.create_index(op.f('uq_salesmen_email'), 'salesmen', ['email'], unique=True)
    op.drop_index(op.f('ix_quotations_customer_phone'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_created_at'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quote_number'), table_name='quotations')
    op.create_index(op.f('ix_quotations_quote_number'), 'quotations', ['quote_number'], unique=False)
    op.create_unique_constraint(op.f('uq_quotations_quote_number'), 'quotations', ['quote_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_quotations_customer_phone'), 'quotations', ['customer_phone'], unique=False)
    op.create_index(op.f('idx_quotations_created_at'), 'quotations', ['created_at'], unique=False)
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.create_index(op.f('idx_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.add_column('password_reset_otps', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_leads_current_owner'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_by'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.create_index(op.f('idx_leads_current_owner'), 'leads', ['current_owner'], unique=False)
    op.create_index(op.f('idx_leads_created_by'), 'leads', ['created_by'], unique=False)
    op.create_index(op.f('idx_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('idx_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.drop_index(op.f('ix_lead_followups_assigned_to'), table_name='lead_followups')
    op.create_unique_constraint(op.f('uq_lead_followups_lead_id'), 'lead_followups', ['lead_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_lead_followups_assigned_to'), 'lead_followups', ['assigned_to'], unique=False)
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.create_index(op.f('uq_admins_email'), 'admins', ['email'], unique=True)
    # ### end Alembic commands ###
